### ISSUE TITLE
You don't need to use let's encrypt

### ISSUE THREAD

**Issue by coolaj86** [11ways/hohenheim#2]
```
    // Set to true to enable letsencrypt (only way to enable https for now)
    letsencrypt: true,
```

You can put the certificates into the `live` config dir with the conventional names and then you don't have to use letsencrypt.

If `configDir` is `~/myproject/etc/acme` then you can put them directly in
```
~/myproject/etc/acme/live/example.com/privkey.pem
~/myproject/etc/acme/live/example.com/cert.pem
~/myproject/etc/acme/live/example.com/chain.pem
~/myproject/etc/acme/live/example.com/fullchain.pem
~/myproject/etc/acme/live/example.com/bundle.pem
```

**Comment by skerit** [comment]
Oh, that's easy. I'll update the docs, thanks for the info!

**Comment by skerit** [comment]
The entire process is pretty focused on letsencrypt, I'll need to change some configuration property & folder names in the future to make it a bit more clear.
